config/routes.rb
ActiveMerchantPayment::Application.routes.draw do
  resources :carts

  resources :line_items

  resources :products

  resources :orders

   root :to => 'products#index'

end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :card_expires_on, :card_type, :cart_id, :first_name, :ip_address, :last_name
  attr_accessible :card_number, :card_verification
  belongs_to :cart
  
  has_many :transactions, :class_name => "OrderTransaction"
  attr_accessor :card_number, :card_verification

  validate :validate_card, :on => :create
  
  validates :first_name,  presence: true
  validates :last_name,  presence: true
  validates :card_number,  presence: true
  validates :card_verification,  presence: true

  def purchase
    response = GATEWAY.purchase(price_in_cents, credit_card, purchase_options) rescue false
    unless response
      self.errors.add("base", "Unable to make payment")
      return false
    end

    if response.success? == false   
      errors[:base] << response.message
      return false       
    end 

    transactions.create!(:action => "purchase", :amount => price_in_cents, :response => response)
    cart.update_attribute(:purchased_at, Time.now) if response.success?
    response.success?
  end
  def authorize


    response = GATEWAY.authorize(price_in_cents, credit_card, purchase_options) rescue false   
    puts "*******************"   
    puts response.inspect    
    puts "************************"
    unless response   
      errors[:base] << "Unable to authorize credit card"
      return false
    end 
      
    
    if response.success? == false   
      if response.avs_result['code'] != "P"  
        errors[:base] << response.avs_result['message']
        return false   
      end
      errors[:base] << response.message
      return false       
    end        

    transactions.create!(:action => "authorize", :amount => price_in_cents, :response => response)
    cart.update_attribute(:purchased_at, Time.now) if response.success?
    response.success?



  end
  def price_in_cents
    (cart.total_price*100).round
  end
 
  private


  def purchase_options
    {  
      
      :ip => ip_address,
      :billing_address => {
        :name     => "Shamsul Haque",
        :address1 => "Rajiv Chowk",
        :city     => "New Delhi",
        :state    => "Delhi",
        :country  => "India",
        :zip      => "110027"
      },
      :x_test_request => false
    }
  end  

  def validate_card
    unless credit_card.valid?
      credit_card.errors.full_messages.each do |message|
        errors[:base] << message
      end
    end
  end

  def credit_card
    @credit_card ||= ActiveMerchant::Billing::CreditCard.new(
      :brand               => card_type,
      :number             => card_number,
      :verification_value => card_verification,
      :month              => card_expires_on.month,
      :year               => card_expires_on.year,
      :first_name         => first_name,
      :last_name          => last_name
    )
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new
    @cart = current_cart
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @cart = current_cart
    @order = Order.new(params[:order])  
    @order.cart_id = current_cart.id     
    session[:cart_id] = nil
    @order.ip_address = request.remote_ip
    
    if @order.valid?
      if @order.save && @order.authorize == true
        if @order.purchase
          render :action => "success"
        else
          render :action => "failure"
        end
      else
        render :action => 'new'  
      end
    else
      render :action => 'new'
    end
    
    
    
#    respond_to do |format|
#      if @order.save
#        format.html { redirect_to @order, notice: 'Order was successfully created.' }
#        format.json { render json: @order, status: :created, location: @order }
#      else
#        format.html { render action: "new" }
#        format.json { render json: @order.errors, status: :unprocessable_entity }
#      end
#    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :card_number %><br />
    <%= f.text_field :card_number %>
  </div>
  <div class="field">
    <%= f.label :card_type %><br />
    <%= f.select :card_type, [["Visa", "visa"], ["MasterCard", "master"], ["Discover", "discover"], ["American Express", "american_express"]] %>
  </div>
  
  <div class="field">
    <%= f.label :card_verification, "Card Verification Value (CVV)" %><br />
    <%= f.text_field :card_verification %>
  </div>
  <div class="field">
    <%= f.label :card_expires_on %><br />
    <%= f.date_select :card_expires_on, :discard_day => true, :start_year => Date.today.year, :end_year => (Date.today.year+10), :add_month_numbers => true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/failure.html.erb
FAILURE

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <tr>
    <th>Cart</th>
    <th>Ip address</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Card type</th>
    <th>Card expires on</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @orders.each do |order| %>
  <tr>
    <td><%= order.cart_id %></td>
    <td><%= order.ip_address %></td>
    <td><%= order.first_name %></td>
    <td><%= order.last_name %></td>
    <td><%= order.card_type %></td>
    <td><%= order.card_expires_on %></td>
    <td><%= link_to 'Show', order %></td>
    <td><%= link_to 'Edit', edit_order_path(order) %></td>
    <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cart:</b>
  <%= @order.cart_id %>
</p>

<p>
  <b>Ip address:</b>
  <%= @order.ip_address %>
</p>

<p>
  <b>First name:</b>
  <%= @order.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @order.last_name %>
</p>

<p>
  <b>Card type:</b>
  <%= @order.card_type %>
</p>

<p>
  <b>Card expires on:</b>
  <%= @order.card_expires_on %>
</p>


<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/orders/success.html.erb
SUCCESS!